### ISSUE TITLE
leaves are green

### ISSUE THREAD

**Issue by larabombonato4** [team-abnormals/autumnity#106]
all of the leaves appear green. i already tried turning on the swap color option but it didnt work. here are the resource packs and mods that i have on my game

resource packs:

mizunos 16 and the CIT + invisible item frame
ghoulcraft
hanana craft
grannys corner
garden breeze
nox better carpets

 mods

fairy lights
JEI
sit
iron age furniture
journey map
pams harvest craft
fast leaf decay

**Comment by HMSRenown** [comment]
I have an idea,please turn "swamp colour" on in settings
