### ISSUE TITLE
Snail shells not dropping

### ISSUE THREAD

**Issue by Juicylene** [team-abnormals/autumnity#116]
im using the mod 2.1.2 version for mc 1.16.5

basically snails dont drop any shells at all, i've tested in creative and killed a LOT of snails to only get slime but no shells, wtf is going on?? is it a mod conflict? am i just REALLY dumb???

**Comment by Markus1002** [comment]
To get snail shells you need to breed two snails with mushroom stew and when the baby grows up it will drop a shell piece.
