### ISSUE TITLE
Snail Loot Tables are invalid

### ISSUE THREAD

**Issue by bolobread** [team-abnormals/autumnity#147]
In the latest version 4.0.1, the snail's loot table does not work.
I was testing with Neruina, which catches issues involving block and entity loot tables, and creating a custom loot table via data pack to change the snail's drops also fails to work.

**Comment by bageldotjpg** [comment]
So a couple things:
1. 4.0.1 isn't the latest version, 5.0.0 is
2. Just tested myself, the snail's loot table works just fine on 4.0.1
3. Vanilla catches issues with block and entity loot tables, you shouldn't need a mod to do that
4. The loot table is data generated in code using mojang's methods, its basically impossible for it to be broken.

So this is either a mod conflict, a mistake, or your own custom loot table is set up incorrectly and causing an error

**Comment by bolobread** [comment]
Ok I tested in an isolated environment and found the issue was with another mod modifying the snail's loot table, was quite the head scratcher. Also this was in 1.19.2.
