### ISSUE TITLE
5.0.1 causes exit -1 error

### ISSUE THREAD

**Issue by GauntAndreX8** [team-abnormals/autumnity#149]
crashes at start of game when 5.0.1 of this mod is installed

**Comment by bageldotjpg** [comment]
Provide your latest.log file but:
- Make sure Blueprint is 7.1.0
- If you have Incubation, make sure it is 4.0.2

**Comment by etherealgears** [comment]
Blueprint 7.1.0 is not available on CurseForge. The latest version there is 7.0.3.

**Comment by bageldotjpg** [comment]
This is because CurseForge hasn't accepted it for some reason, it is available on modrinth for now https://modrinth.com/mod/blueprint

**Comment by GauntAndreX8** [comment]
Will it be on curseforge later tho?

**Comment by bageldotjpg** [comment]
Yes, as I said curse just hasn't accepted it yet, and for now its only available on modrinth because of this
