### ISSUE TITLE
[1.20.1] Maple Leaf Banner Pattern is missing its recipe

### ISSUE THREAD

**Issue by Not-February** [team-abnormals/autumnity#152]
There isn't currently a recipe for the Maple Leaf Banner Pattern in the mod file. It's supposed to be craftable with a syrup bottle and paper, right? 

``Forge 47.3.0``
``Blueprint 7.1.0``
``Autumnity 5.0.1``

**Comment by bageldotjpg** [comment]
It is now exclusive to the Maple Witch Hut Loot
