### ISSUE TITLE
Couldn't parse data file autumnity:foul_berry_sack_uncompress

### ISSUE THREAD

**Issue by alfuken** [team-abnormals/autumnity#41]
Error message: Couldn't parse data file autumnity:foul_berry_sack_uncompress from autumnity:recipes/foul_berry_sack_uncompress.json

Version: autumnity-1.3.3-1.15.2.jar
Other mods: Quark-r2.1-245.jar, Abnormals-Core-1.15.2-1.0.6.jar

Forge: 31.2.47

**Comment by bageldotjpg** [comment]
Unfortunately, 1.15.2 is no longer supported. This is fixed in later versions
