### ISSUE TITLE
Leaves not displaying color correctly 

### ISSUE THREAD

**Issue by hampus074** [team-abnormals/autumnity#45]
I am unsure if this is a optifine issue or with this mod but when i have optifine installed and the Stay True resourcepack all the leaves from this mod turn green. Is there any way to fix this? I really love the different colors the trees have but can't use them :(

My Install (I have other mods but the problem occurs only with these):

Minecraft 1.16.4
abnormals_core-1.16.4-3.0.5
autumnity-1.16.4-2.0.1
preview_OptiFine_1.16.4_HD_U_G6_pre10
release 1.16.4-forge-35.1.28

and the Stay True 1.16 resource pack

**Comment by bageldotjpg** [comment]
This is an issue with the stay true resource pack
