### ISSUE TITLE
Snails

### ISSUE THREAD

**Issue by EspadaLegend** [team-abnormals/autumnity#49]
Snails when fed aren't producing Slime as intended. Rather when you feed a snail mushroom they are stuck in trying to produce slime and cannot eat again.

**Comment by Vaelzan** [comment]
For additional context, it seems that some people are having it work normally and some do not.

I noticed it mentioned on the Team Abnormals Discord that somebody else was having trouble with it https://discord.com/channels/650003402218274816/729321766748553296/797968202923638844 but it is working in my own testing.

**Comment by Markus1002** [comment]
Snails only produce slime on blocks with air above them. Perhaps the reason they can't produce slime is that grass or some other plant is blocking them from doing so.

**Comment by EspadaLegend** [comment]
> Snails only produce slime on blocks with air above them. Perhaps the reason they can't produce slime is that grass or some other plant is blocking them from doing so.

The issue is its stuck trying to make slime. And in doing so they cannot eat again so they just become a walking slime sprite and that's it.

**Comment by Markus1002** [comment]
That's not what I meant. Snail slime doesn't replace blocks like tall grass or flowers so if a snail is inside grass it won't produce slime. Try feeding the snail in an environment without any blocks that you can walk through and try to see if the problem persists.

**Comment by EspadaLegend** [comment]
Guy. I cannot feed the snail. >>>>>>When I do they are stuck in "PRODUCE SLIME" in this case you cannot feed the snail. I know what the slime looks like. I know how it works. this wasnt done near any grass at all so it clearly has nothing to do with grass at all.
