### ISSUE TITLE
Snails consume all mushroom stew in a stack

### ISSUE THREAD

**Issue by thenewdreamer** [team-abnormals/autumnity#56]
If another mod makes mushroom stew stackable beyond 1, attempting to breed a snail with a stack of multiple mushroom stew with replace the whole stack with a single empty bowl

**Comment by Markus1002** [comment]
Do you have any examples of mods that do that so I can test with them?

**Comment by thenewdreamer** [comment]
The mod I was using was Charm https://www.curseforge.com/minecraft/mc-mods/charm

(You can also use commands to create stacked mushroom stew but it is apparently vanilla behavior that players eating stacked mushroom stew also consume the whole stack, and that's something Charm fixes)

**Comment by Markus1002** [comment]
Fixed.
