### ISSUE TITLE
All autumn leaves are green. 

### ISSUE THREAD

**Issue by devinrsanders** [team-abnormals/autumnity#59]
All of the maple leaves are the color of the green maple leaves. I tried removing all of my resource packs but that wasn't the answer.

**Comment by Markus1002** [comment]
The problem is probably caused by another mod. Try removing some of them that might affect leaf colors, like Optifine.

**Comment by devinrsanders** [comment]
Thanks! looks like optifine was the problem, I had swamp colors turned off which somehow affected the leaves.
