### ISSUE TITLE
Twig Nests cause massive frame drops when removing and inputting items.

### ISSUE THREAD

**Issue by dmsw0303** [team-abnormals/autumnity#74]
The frame drops you get from adding and removing a single item happen quickly enough that it's actually hard to notice the frame drops, but if you completely fill one with some eggs and then try removing all of them semi-quickly, the game will drop hundreds of frames. This also works vice versa.

Java 15, in case that ends up mattering.

**Comment by Markus1002** [comment]
You should post this issue in the Environmental github, not Autumnity.
