### ISSUE TITLE
Mod compat with Refined Storage

### ISSUE THREAD

**Issue by tikiMC** [team-abnormals/autumnity#88]
The two banner patterns this mod adds have missing texture when Refined Storage is installed for whatever reason.
I tested refined storage with another banner mod, additional banners and those seem to work. The same issue persists however with alexsmobs banner patterns so whatever autumnity and alexs has in common I assume is the issue

**Comment by bageldotjpg** [comment]
Should be fixed as of Refined Storage 1.9.13
