### ISSUE TITLE
Biomes of loaded chunks change when updating from 1.16.1 to any higher

### ISSUE THREAD

**Issue by olegreg76** [team-abnormals/autumnity#89]
Biomes of chunks loaded in 1.16.1 change to different biomes when updating. Blocks are still there, but biome behavior changes to the "new" biome.

**Comment by bageldotjpg** [comment]
Yeah, nothing we can do about this. This will occur with any biome mod.
Make sure you're on the latest forge & try installing chocolate fix and then trying, but there is nothing we can really do to help.
Worldgen was heavily refactored in 1.16.2 and can cause a lot of issues when trying to move worlds over.
